version: '3.7'
services:
  db:
    image: mysql:8.0
    volumes:
      - ${DATABASE_DIR}:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - localnetwork

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - localnetwork
    depends_on:
      - db

networks:
  localnetwork: